# Generated by Django 5.0.4 on 2024-05-02 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='map.item')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ThreatInfo',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('rate', models.SmallIntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.item')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('rate', models.SmallIntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('threat_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.threatinfo')),
            ],
        ),
    ]
